[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    symlink://../..  ; Logger library
build_flags = 
    -Werror=unused-result
    -D USE_CUSTOM_LOGGER
    -D CONFIG_LOG_BUFFER_SIZE=256