[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    symlink://../..  ; Logger library
build_flags = 
    -Werror=unused-result
    -D USE_CUSTOM_LOGGER
    -D CONFIG_LOG_BUFFER_SIZE=256
[env:core2_espressif32]
extends = env:esp32dev
platform = espressif32
